# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

#List for test
ponentes:
  ponente1:
    nombre: Nombre Ponente 1
    text: Texto Ponente 1
    image: fa-cloud
  ponente2:
    nombre: Nombre Ponente 2
    text: Texto Ponente 2
    image: fa-compass
  ponente3:
    nombre: Nombre Ponente 3
    text: Texto Ponente 3
    image: fa-flask
  ponente4:
    nombre: Nombre Ponente 4
    text: Texto Ponente 4
    image: fa-shield
