# Site settings
title:  as
email:  qssq
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line: lalalala
  - line: lelelelelel
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman

#List for test
ponentes:
  - name: Nombre Ponente 1
    text: Texto Ponente 1
    image: fa-cloud
  - name: Nombre Ponente 2
    text: Texto Ponente 2
    image: fa-compass
  - name: Nombre Ponente 3
    text: Texto Ponente 3
    image: fa-flask
  - name: Nombre Ponente 4
    text: Texto Ponente 4
    image: fa-shield
 -  name: Nombre Ponente 12
    text: Texto Ponente 12
    image: fa-cloud
  - name: Nombre Ponente 22
    text: Texto Ponente 22
    image: fa-compass
  - name: Nombre Ponente 32
    text: Texto Ponente 32
    image: fa-flask
  - name: Nombre Ponente 42
    text: Texto Ponente 42
    image: fa-shield
  - name: Nombre Ponente 13
    text: Texto Ponente 13
    image: fa-cloud
